name: Auto-move PR to Review

on:
  pull_request:
    types: [opened, ready_for_review, review_requested]

permissions:
  pull-requests: write
  repository-projects: write

jobs:
  move-to-review:
    name: Move PR to "In Review" column
    runs-on: ubuntu-latest
    # Skip draft PRs
    if: ${{ !github.event.pull_request.draft }}
    steps:
      - name: Move to In Review
        uses: alex-page/github-project-automation-plus@v0.9.0
        with:
          project: tofu-uptrace-provider Development Roadmap
          column: ðŸ‘€ In Review
          repo-token: ${{ secrets.GITHUB_TOKEN }}
